name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Start Python 3 HTTP server
        run: python3 -m http.server 8000 &
     #   background: true
      - name: Cypress_run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress open  
        continue-on-error: true  # Continue even if Cypress tests fail  
      - name: Check Cypress test status
        id: check_status
       # run: echo "::set-output name=status::${{ job.error }}${{ job.Error}}"
        if: steps.Cypress_run.outcome != 'success' 
        run: echo "failure"

      - name: Create issue on failure
        if: ${{ steps.check_status.outputs == 'failure' }}
        run: |
          GITHUB_TOKEN=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
          REPO_OWNER=ahegde3
          REPO_NAME=test-actions
          ISSUE_TITLE="Cypress tests failed"
          ISSUE_BODY="Cypress tests failed. Check the workflow run for more details."
  
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues" \
            -d "{\"title\":\"$ISSUE_TITLE\",\"body\":\"$ISSUE_BODY\"}"
  
   
