name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Start Python 3 HTTP server
        run: python3 -m http.server 8000 &
     #   background: true
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress open    
     - name: Check Cypress test status
        id: check_status
        run: echo "::set-output name=status::${{ job.status }}"
        continue-on-error: true
   
